version: '3'

services:
  base: &base
    image: chatwoot/chatwoot:latest
    platform: 'linux/x86_64'
    env_file: .env ## Change this file for customized env variables
    volumes:
      - /tmp/storage:/app/storage

  rails:
    <<: *base
    external_links:
      - postgres
      - redis
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    platform: 'linux/x86_64'
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    networks:
      - external-network

  sidekiq:
    <<: *base
    external_links:
      - postgres
      - redis
    platform: 'linux/x86_64'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    networks:
      - external-network

networks:
  external-network:
    external: true



  # postgres:
  #   image: postgres:12
  #   restart: always
  #   ports:
  #     - '127.0.0.1:5432:5432'
  #   volumes:
  #     - /data/postgres:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=chatwoot
  #     - POSTGRES_USER=postgres
  #     # Please provide your own password.
  #     - POSTGRES_PASSWORD=

  # redis:
  #   image: redis:alpine
  #   restart: always
  #   command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
  #   env_file: .env
  #   volumes:
  #     - /data/redis:/data
  #   ports:
  #     - '127.0.0.1:6379:6379'
